---
- name: Check if swarm initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true

- name: Initialise swarm
  when: swarm_status.rc != 0
  shell: docker swarm init

- name: Get worker key
  when: swarm_status.rc != 0
  shell: docker swarm join-token worker -q
  register: worker_token
